development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: github_webhooks_development
  pool:     5
  username: app
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: app_test
  pool:     5
  username: app
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: app_production
  pool:     5
  username: app
  password:
  template: template0
